### ISSUE TITLE
Can't call method "set" on unblessed reference at .//HLstats_EventHandlers.plib line 564.

### ISSUE THREAD

**Issue by theck1** [startersclan/source-udp-forwarder#52]
Had a running system working fine with 1.11.0 (?) for a long time.

However, after a restore from a backup after hdd failure,  I restored from backup, but never got it to work properly again. 
I created a new DB, and updated hlstatsce to version 1.11.2.

The daemon crashes sometimes, and the hlstats daemon gives this error message.
One player does not get any kills registered, and it seems to crash everytime that specific player joins the game / mapchange.
It registers the other players fine it seems, until he joins and the daemon crashes. This can just be random behaviour.

Daemon crash error message:
Can't call method "set" on unblessed reference at .//HLstats_EventHandlers.plib line 564.

Any tips?

**Comment by leojonathanoh** [comment]
[v1.11.3](https://github.com/startersclan/hlstatsx-community-edition/releases) fixed that bug. Simply upgrade and it will be fixed.

In the future, please open daemon issues at https://github.com/startersclan/hlstatsx-community-edition.
